-- WhatsApp session tracking for the Task-Fix chatbot
-- Run this in your Supabase Dashboard → SQL Editor

CREATE TABLE IF NOT EXISTS public.whatsapp_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone text NOT NULL UNIQUE,
  step text NOT NULL DEFAULT 'welcome',
  language text NOT NULL DEFAULT 'en',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Allow the edge function (service role) full access
ALTER TABLE public.whatsapp_sessions DISABLE ROW LEVEL SECURITY;
