create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  postcode text not null,
  service text not null,
  service_datetime timestamptz not null,
  property_size text,
  description text not null,
  photos jsonb not null default '[]'::jsonb,
  source text,
  status text not null default 'new',
  preferred_service_slug text,
  created_at timestamptz not null default now()
);

-- Disable RLS for public contact form submissions
alter table public.contact_requests disable row level security;

-- Ensure existing databases pick up the new email column
alter table public.contact_requests add column if not exists email text;

-- Create a storage bucket for contact photos if it doesn't exist
insert into storage.buckets (id, name, public)
values ('contact_photos', 'contact_photos', true)
on conflict (id) do nothing;

-- Set up storage policies for the contact_photos bucket
-- 1. Allow public to upload (insert) files
create policy "Public Upload"
on storage.objects for insert
with check (bucket_id = 'contact_photos');

-- 2. Allow public to view files
create policy "Public View"
on storage.objects for select
using (bucket_id = 'contact_photos');

